[package]
name = "render_sprite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ABC_lumenpyx = {path = "../../."}
ABC_Game_Engine = { git = "https://github.com/ABC-Engine/ABC-Game-Engine"}
